{
    "type": "error",
    "data": "Error executing verb \"create_base_entity_graph\" in create_base_entity_graph: Columns must be same length as key",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\workflows\\v1\\subflows\\create_base_entity_graph.py\", line 51, in create_base_entity_graph\n    output = await create_base_entity_graph_flow(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\flows\\create_base_entity_graph.py\", line 77, in create_base_entity_graph\n    clustered = cluster_graph(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\operations\\cluster_graph.py\", line 89, in cluster_graph\n    output[[level_to, to]] = pd.DataFrame(output[to].tolist(), index=output.index)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n    self._setitem_array(key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4341, in _setitem_array\n    check_key_length(self.columns, key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\indexers\\utils.py\", line 390, in check_key_length\n    raise ValueError(\"Columns must be same length as key\")\nValueError: Columns must be same length as key\n",
    "source": "Columns must be same length as key",
    "details": null
}
{
    "type": "error",
    "data": "Error running pipeline!",
    "stack": "Traceback (most recent call last):\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\run\\run.py\", line 273, in run_pipeline\n    result = await _process_workflow(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\run\\workflow.py\", line 105, in _process_workflow\n    result = await workflow.run(context, callbacks)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 369, in run\n    timing = await self._execute_verb(node, context, callbacks)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\workflows\\v1\\subflows\\create_base_entity_graph.py\", line 51, in create_base_entity_graph\n    output = await create_base_entity_graph_flow(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\flows\\create_base_entity_graph.py\", line 77, in create_base_entity_graph\n    clustered = cluster_graph(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\operations\\cluster_graph.py\", line 89, in cluster_graph\n    output[[level_to, to]] = pd.DataFrame(output[to].tolist(), index=output.index)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n    self._setitem_array(key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4341, in _setitem_array\n    check_key_length(self.columns, key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\indexers\\utils.py\", line 390, in check_key_length\n    raise ValueError(\"Columns must be same length as key\")\nValueError: Columns must be same length as key\n",
    "source": "Columns must be same length as key",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_base_entity_graph\" in create_base_entity_graph: Columns must be same length as key",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\workflows\\v1\\subflows\\create_base_entity_graph.py\", line 51, in create_base_entity_graph\n    output = await create_base_entity_graph_flow(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\flows\\create_base_entity_graph.py\", line 77, in create_base_entity_graph\n    clustered = cluster_graph(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\operations\\cluster_graph.py\", line 89, in cluster_graph\n    output[[level_to, to]] = pd.DataFrame(output[to].tolist(), index=output.index)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n    self._setitem_array(key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4341, in _setitem_array\n    check_key_length(self.columns, key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\indexers\\utils.py\", line 390, in check_key_length\n    raise ValueError(\"Columns must be same length as key\")\nValueError: Columns must be same length as key\n",
    "source": "Columns must be same length as key",
    "details": null
}
{
    "type": "error",
    "data": "Error running pipeline!",
    "stack": "Traceback (most recent call last):\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\run\\run.py\", line 273, in run_pipeline\n    result = await _process_workflow(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\run\\workflow.py\", line 105, in _process_workflow\n    result = await workflow.run(context, callbacks)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 369, in run\n    timing = await self._execute_verb(node, context, callbacks)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\workflows\\v1\\subflows\\create_base_entity_graph.py\", line 51, in create_base_entity_graph\n    output = await create_base_entity_graph_flow(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\flows\\create_base_entity_graph.py\", line 77, in create_base_entity_graph\n    clustered = cluster_graph(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\operations\\cluster_graph.py\", line 89, in cluster_graph\n    output[[level_to, to]] = pd.DataFrame(output[to].tolist(), index=output.index)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n    self._setitem_array(key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4341, in _setitem_array\n    check_key_length(self.columns, key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\indexers\\utils.py\", line 390, in check_key_length\n    raise ValueError(\"Columns must be same length as key\")\nValueError: Columns must be same length as key\n",
    "source": "Columns must be same length as key",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_base_entity_graph\" in create_base_entity_graph: Columns must be same length as key",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\workflows\\v1\\subflows\\create_base_entity_graph.py\", line 51, in create_base_entity_graph\n    output = await create_base_entity_graph_flow(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\flows\\create_base_entity_graph.py\", line 77, in create_base_entity_graph\n    clustered = cluster_graph(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\operations\\cluster_graph.py\", line 89, in cluster_graph\n    output[[level_to, to]] = pd.DataFrame(output[to].tolist(), index=output.index)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n    self._setitem_array(key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4341, in _setitem_array\n    check_key_length(self.columns, key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\indexers\\utils.py\", line 390, in check_key_length\n    raise ValueError(\"Columns must be same length as key\")\nValueError: Columns must be same length as key\n",
    "source": "Columns must be same length as key",
    "details": null
}
{
    "type": "error",
    "data": "Error running pipeline!",
    "stack": "Traceback (most recent call last):\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\run\\run.py\", line 273, in run_pipeline\n    result = await _process_workflow(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\run\\workflow.py\", line 105, in _process_workflow\n    result = await workflow.run(context, callbacks)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 369, in run\n    timing = await self._execute_verb(node, context, callbacks)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\workflows\\v1\\subflows\\create_base_entity_graph.py\", line 51, in create_base_entity_graph\n    output = await create_base_entity_graph_flow(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\flows\\create_base_entity_graph.py\", line 77, in create_base_entity_graph\n    clustered = cluster_graph(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\operations\\cluster_graph.py\", line 89, in cluster_graph\n    output[[level_to, to]] = pd.DataFrame(output[to].tolist(), index=output.index)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n    self._setitem_array(key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4341, in _setitem_array\n    check_key_length(self.columns, key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\indexers\\utils.py\", line 390, in check_key_length\n    raise ValueError(\"Columns must be same length as key\")\nValueError: Columns must be same length as key\n",
    "source": "Columns must be same length as key",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_base_entity_graph\" in create_base_entity_graph: Columns must be same length as key",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\workflows\\v1\\subflows\\create_base_entity_graph.py\", line 51, in create_base_entity_graph\n    output = await create_base_entity_graph_flow(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\flows\\create_base_entity_graph.py\", line 77, in create_base_entity_graph\n    clustered = cluster_graph(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\operations\\cluster_graph.py\", line 89, in cluster_graph\n    output[[level_to, to]] = pd.DataFrame(output[to].tolist(), index=output.index)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n    self._setitem_array(key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4341, in _setitem_array\n    check_key_length(self.columns, key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\indexers\\utils.py\", line 390, in check_key_length\n    raise ValueError(\"Columns must be same length as key\")\nValueError: Columns must be same length as key\n",
    "source": "Columns must be same length as key",
    "details": null
}
{
    "type": "error",
    "data": "Error running pipeline!",
    "stack": "Traceback (most recent call last):\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\run\\run.py\", line 273, in run_pipeline\n    result = await _process_workflow(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\run\\workflow.py\", line 105, in _process_workflow\n    result = await workflow.run(context, callbacks)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 369, in run\n    timing = await self._execute_verb(node, context, callbacks)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\workflows\\v1\\subflows\\create_base_entity_graph.py\", line 51, in create_base_entity_graph\n    output = await create_base_entity_graph_flow(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\flows\\create_base_entity_graph.py\", line 77, in create_base_entity_graph\n    clustered = cluster_graph(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\operations\\cluster_graph.py\", line 89, in cluster_graph\n    output[[level_to, to]] = pd.DataFrame(output[to].tolist(), index=output.index)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n    self._setitem_array(key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4341, in _setitem_array\n    check_key_length(self.columns, key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\indexers\\utils.py\", line 390, in check_key_length\n    raise ValueError(\"Columns must be same length as key\")\nValueError: Columns must be same length as key\n",
    "source": "Columns must be same length as key",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_base_entity_graph\" in create_base_entity_graph: Columns must be same length as key",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\workflows\\v1\\subflows\\create_base_entity_graph.py\", line 51, in create_base_entity_graph\n    output = await create_base_entity_graph_flow(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\flows\\create_base_entity_graph.py\", line 77, in create_base_entity_graph\n    clustered = cluster_graph(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\operations\\cluster_graph.py\", line 89, in cluster_graph\n    output[[level_to, to]] = pd.DataFrame(output[to].tolist(), index=output.index)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n    self._setitem_array(key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4341, in _setitem_array\n    check_key_length(self.columns, key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\indexers\\utils.py\", line 390, in check_key_length\n    raise ValueError(\"Columns must be same length as key\")\nValueError: Columns must be same length as key\n",
    "source": "Columns must be same length as key",
    "details": null
}
{
    "type": "error",
    "data": "Error running pipeline!",
    "stack": "Traceback (most recent call last):\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\run\\run.py\", line 273, in run_pipeline\n    result = await _process_workflow(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\run\\workflow.py\", line 105, in _process_workflow\n    result = await workflow.run(context, callbacks)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 369, in run\n    timing = await self._execute_verb(node, context, callbacks)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\workflows\\v1\\subflows\\create_base_entity_graph.py\", line 51, in create_base_entity_graph\n    output = await create_base_entity_graph_flow(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\flows\\create_base_entity_graph.py\", line 77, in create_base_entity_graph\n    clustered = cluster_graph(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\operations\\cluster_graph.py\", line 89, in cluster_graph\n    output[[level_to, to]] = pd.DataFrame(output[to].tolist(), index=output.index)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n    self._setitem_array(key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4341, in _setitem_array\n    check_key_length(self.columns, key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\indexers\\utils.py\", line 390, in check_key_length\n    raise ValueError(\"Columns must be same length as key\")\nValueError: Columns must be same length as key\n",
    "source": "Columns must be same length as key",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_base_entity_graph\" in create_base_entity_graph: Columns must be same length as key",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\workflows\\v1\\subflows\\create_base_entity_graph.py\", line 51, in create_base_entity_graph\n    output = await create_base_entity_graph_flow(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\flows\\create_base_entity_graph.py\", line 77, in create_base_entity_graph\n    clustered = cluster_graph(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\operations\\cluster_graph.py\", line 89, in cluster_graph\n    output[[level_to, to]] = pd.DataFrame(output[to].tolist(), index=output.index)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n    self._setitem_array(key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4341, in _setitem_array\n    check_key_length(self.columns, key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\indexers\\utils.py\", line 390, in check_key_length\n    raise ValueError(\"Columns must be same length as key\")\nValueError: Columns must be same length as key\n",
    "source": "Columns must be same length as key",
    "details": null
}
{
    "type": "error",
    "data": "Error running pipeline!",
    "stack": "Traceback (most recent call last):\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\run\\run.py\", line 273, in run_pipeline\n    result = await _process_workflow(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\run\\workflow.py\", line 105, in _process_workflow\n    result = await workflow.run(context, callbacks)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 369, in run\n    timing = await self._execute_verb(node, context, callbacks)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\workflows\\v1\\subflows\\create_base_entity_graph.py\", line 51, in create_base_entity_graph\n    output = await create_base_entity_graph_flow(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\flows\\create_base_entity_graph.py\", line 77, in create_base_entity_graph\n    clustered = cluster_graph(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\operations\\cluster_graph.py\", line 89, in cluster_graph\n    output[[level_to, to]] = pd.DataFrame(output[to].tolist(), index=output.index)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4299, in __setitem__\n    self._setitem_array(key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\frame.py\", line 4341, in _setitem_array\n    check_key_length(self.columns, key, value)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\pandas\\core\\indexers\\utils.py\", line 390, in check_key_length\n    raise ValueError(\"Columns must be same length as key\")\nValueError: Columns must be same length as key\n",
    "source": "Columns must be same length as key",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_base_entity_graph\" in create_base_entity_graph: EmptyNetworkError",
    "stack": "Traceback (most recent call last):\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\workflows\\v1\\subflows\\create_base_entity_graph.py\", line 51, in create_base_entity_graph\n    output = await create_base_entity_graph_flow(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\flows\\create_base_entity_graph.py\", line 77, in create_base_entity_graph\n    clustered = cluster_graph(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\operations\\cluster_graph.py\", line 46, in cluster_graph\n    communities = run_layout(strategy, input)\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\operations\\cluster_graph.py\", line 134, in run_layout\n    clusters = run_leiden(graph, strategy)\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\operations\\cluster_graph.py\", line 157, in run_leiden\n    node_id_to_community_map = _compute_leiden_communities(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\operations\\cluster_graph.py\", line 195, in _compute_leiden_communities\n    community_mapping = hierarchical_leiden(\n  File \"<@beartype(graspologic.partition.leiden.hierarchical_leiden) at 0x2250fedf5b0>\", line 304, in hierarchical_leiden\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\graspologic\\partition\\leiden.py\", line 588, in hierarchical_leiden\n    hierarchical_clusters_native = gn.hierarchical_leiden(\nleiden.EmptyNetworkError: EmptyNetworkError\n",
    "source": "EmptyNetworkError",
    "details": null
}
{
    "type": "error",
    "data": "Error running pipeline!",
    "stack": "Traceback (most recent call last):\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\run\\run.py\", line 273, in run_pipeline\n    result = await _process_workflow(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\run\\workflow.py\", line 105, in _process_workflow\n    result = await workflow.run(context, callbacks)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 369, in run\n    timing = await self._execute_verb(node, context, callbacks)\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\datashaper\\workflow\\workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\workflows\\v1\\subflows\\create_base_entity_graph.py\", line 51, in create_base_entity_graph\n    output = await create_base_entity_graph_flow(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\flows\\create_base_entity_graph.py\", line 77, in create_base_entity_graph\n    clustered = cluster_graph(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\operations\\cluster_graph.py\", line 46, in cluster_graph\n    communities = run_layout(strategy, input)\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\operations\\cluster_graph.py\", line 134, in run_layout\n    clusters = run_leiden(graph, strategy)\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\operations\\cluster_graph.py\", line 157, in run_leiden\n    node_id_to_community_map = _compute_leiden_communities(\n  File \"E:\\works\\python\\graphrag-main\\graphrag\\index\\operations\\cluster_graph.py\", line 195, in _compute_leiden_communities\n    community_mapping = hierarchical_leiden(\n  File \"<@beartype(graspologic.partition.leiden.hierarchical_leiden) at 0x2250fedf5b0>\", line 304, in hierarchical_leiden\n  File \"C:\\Users\\dz2\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\graphrag-Uz205k9x-py3.10\\lib\\site-packages\\graspologic\\partition\\leiden.py\", line 588, in hierarchical_leiden\n    hierarchical_clusters_native = gn.hierarchical_leiden(\nleiden.EmptyNetworkError: EmptyNetworkError\n",
    "source": "EmptyNetworkError",
    "details": null
}
